config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#main_page'
  resources:tweets
  resources:profiles

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	validates :content, length: {maximum: 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
	def new
		@profile = Profile.new
	end
	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if@profile.save
			flash[:success] = "you have created a profile"
			redirect_to new_tweet_path
		else
			render 'new'
		end
	end
	def profile_params
		params.require(:profile).permit(:first_name, :picture, :description)
	end
	def show
		@profile = Profile.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
		if user_signed_in?
			if current_user.profile
				redirect_to new_tweet_path
			else
				redirect_to new_profile_path
			end
		end
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!
	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user
		if @tweet.save
			flash[:success] = "You Tweeted!"
			redirect_to new_tweet_path
		else 
			render 'new'
		end
	end

	def tweet_params
		params.require(:tweet).permit(:content)
	end

	def index
		@tweets = Tweet.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path)
		class_name = current_page?(link_path) ? 'active' : ''
		content_tag(:li, :class => class_name) do 
			link_to link_text, link_path
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Htwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body background="../assets/background.jpg">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Twitter", root_path, class: 'navbar-brand' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li>
        	<%= nav_link "New Tweet", new_tweet_path %>
        	<span class="sr-only">(current)</span></a>
        </li>
        <li><%= nav_link "NewsFeed", tweets_path %></a>
        </li>
      </ul>
     <%end%>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <% if user_signed_in? %>
        <%= link_to("Log Out",destroy_user_session_path, method: :delete) %>
        <% else %>
        	<%= link_to "Sign In", new_user_session_path %>
        <% end %>

        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? && current_user.profile %>
              <li><%= link_to "My Profile",profile_path(current_user.profile) %></li>
            <% end %>

            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class = "container">
	<% flash.each do |key,value| %>
	<!-- <%=key%> -->
<div class="alert alert-success alert-dismissible" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  	<span aria-hidden="true">&times;</span>
	  </button>
	  <%= value %>
	</div>
	<% end %>
  <div class="container padding-top-ten">
    <%= yield %>
  </div>
</div>

</body>

<style>
body{
    background-color: #525252;
}
.centered-form{
	margin-top: 100px;
}

.centered-form .panel{
	background: rgba(255, 255, 255, 0.8);
	box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
}
</style>
</html>

app/views/profiles/new.html.erb
<%= simple_form_for @profile do |f| %>
	<%= f.input :picture %>
	<%= f.input :first_name %>	
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/profiles/show.html.erb
<%= @profile.first_name %>
<%= @profile.description %>

app/views/static_pages/main_page.erb
<br/>
<br/>
<br/>
main page

app/views/tweets/index.html.erb
<ul class = "list-group">
<% @tweets.each do |tweet| %>
	<li class="list-group-item"> 
		<%= tweet.content %> <%= tweet.user.email%>
	</li>
<%end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
	<%= f.input :content %>
	<%= f.button :submit, value: "Create Tweet" %>
<% end %>